const MIN_MULTIPLIER = 2;
const MAX_MULTIPLIER = 9;

const MATH_CONFIG = {
	MIN_MULTIPLIER,
	MAX_MULTIPLIER,
	MULTIPLIER_LIST_LENGTH: MAX_MULTIPLIER - MIN_MULTIPLIER + 1,
	VERSIONS_LIST: {
		LENGTH: 4,
		DELTA: 3,
	}
};

export default MATH_CONFIG;