
const MIN_MULTIPLIER = 2;
const MAX_MULTIPLIER = 9;

export const MATH_CONFIG = {
	MULTIPLICATION: {
		MIN_MULTIPLIER,
		MAX_MULTIPLIER,
		MULTIPLIER_LIST_LENGTH: MAX_MULTIPLIER - MIN_MULTIPLIER + 1,
		VERSIONS_LIST: {
			MIN: MIN_MULTIPLIER,
			MAX: MAX_MULTIPLIER,
			LENGTH: 4,
			DELTA: 3,
		}
	}
};