
const MAX_MULTIPLIER = 9;
const MIN_MULTIPLIER = 2;

export const MATH_CONFIG = {
	MULTIPLICATION: {
		MAX_MULTIPLIER,
		MIN_MULTIPLIER,
		MULTIPLIER_LIST_LENGTH: MAX_MULTIPLIER - MIN_MULTIPLIER + 1,

	}
};